site_name: zk-lab
site_url: https://lambdasistemi.github.io/zk-lab/
repo_url: https://github.com/lambdasistemi/zk-lab
repo_name: lambdasistemi/zk-lab

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: amber
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.path
    - navigation.top
    - content.code.copy
    - toc.integrate

markdown_extensions:
  - admonition
  - tables
  - footnotes
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
